create table if not exists rsvps (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_slug text not null check (
    event_slug in ('austin', 'minneapolis', 'mcallen', 'monterrey')
  ),
  event_city text not null,
  event_date date not null,
  name text not null,
  phone text not null,
  guests integer not null check (guests between 1 and 4),
  attending boolean not null,
  overnight_travel boolean not null default false,
  note text not null,
  user_agent text
);

create index if not exists rsvps_event_slug_idx on rsvps (event_slug);
create index if not exists rsvps_created_at_idx on rsvps (created_at desc);
